spring:
  application:
    name: lead-rocket-backend

  profiles:
    active: dev

    data:
      redis:
        host: redis-11566.crce206.ap-south-1-1.ec2.cloud.redislabs.com
        port: 11566
        username: default
        password: ${REDIS_PASSWORD}
        ssl: true
        timeout: 5s

    cache:
      type: redis


server:
  port: 8080
